# Generated by Django 3.2.9 on 2021-12-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_details',
            table='Book_details',
        ),
    ]
